/**
 * 统一错误码字典（前端消费版本）。
 *
 * 与后端 `com.wenda.error.ErrorCode` 1:1 对齐；后端在
 * `ApiResponse.code` 字段返回此处枚举的字符串值。前端按 code 提示用户、
 * 上报埋点、决定路由跳转。
 *
 * 基线：api_error_code_dictionary_v1.0.md + 接口文档 v0.2 §2.6
 */

export const ErrorCode = {
  OK: 'OK',
  CREATED: 'CREATED',
  ACCEPTED: 'ACCEPTED',
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  ACCESS_DENIED: 'ACCESS_DENIED',
  SCOPE_FORBIDDEN: 'SCOPE_FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  BUSINESS_STATE_INVALID: 'BUSINESS_STATE_INVALID',
  SCHOOL_SCOPE_REQUIRED: 'SCHOOL_SCOPE_REQUIRED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_SECURITY_SCAN_PENDING: 'FILE_SECURITY_SCAN_PENDING',
  FILE_SECURITY_SCAN_FAILED: 'FILE_SECURITY_SCAN_FAILED',
  FILE_ACCESS_DENIED: 'FILE_ACCESS_DENIED',
  AI_PROVIDER_DISABLED: 'AI_PROVIDER_DISABLED',
  AI_OUTPUT_SCHEMA_INVALID: 'AI_OUTPUT_SCHEMA_INVALID',
  AI_TASK_FAILED: 'AI_TASK_FAILED',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_ALREADY_RUNNING: 'TASK_ALREADY_RUNNING',
  TASK_TIMEOUT: 'TASK_TIMEOUT',
  REPORT_TEMPLATE_NOT_FOUND: 'REPORT_TEMPLATE_NOT_FOUND',
  REPORT_FILE_NOT_READY: 'REPORT_FILE_NOT_READY',
  KNOWLEDGE_SOURCE_DISABLED: 'KNOWLEDGE_SOURCE_DISABLED',
  KNOWLEDGE_SEARCH_UNSUPPORTED_FILTER: 'KNOWLEDGE_SEARCH_UNSUPPORTED_FILTER',
  AUTHORIZATION_EXPIRED: 'AUTHORIZATION_EXPIRED',
  AUTHORIZATION_REVOKED: 'AUTHORIZATION_REVOKED',
  DISPLAY_SCOPE_FORBIDDEN: 'DISPLAY_SCOPE_FORBIDDEN',
  IMPORT_TEMPLATE_INVALID: 'IMPORT_TEMPLATE_INVALID',
  IMPORT_CONFLICT_REQUIRES_DECISION: 'IMPORT_CONFLICT_REQUIRES_DECISION',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DEPENDENCY_UNAVAILABLE: 'DEPENDENCY_UNAVAILABLE'
} as const

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode]

export interface ApiResponse<T> {
  success: boolean
  code: ErrorCodeValue | string
  message: string
  data: T
  requestId?: string
  timestamp?: string
  details?: Array<Record<string, unknown>>
}

export function isAuthError(code: string | undefined): boolean {
  return code === ErrorCode.UNAUTHORIZED || code === ErrorCode.TOKEN_EXPIRED
}

export function isForbidden(code: string | undefined): boolean {
  return (
    code === ErrorCode.FORBIDDEN ||
    code === ErrorCode.ACCESS_DENIED ||
    code === ErrorCode.SCOPE_FORBIDDEN
  )
}
